-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 22:45:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema insumos_vet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema insumos_vet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insumos_vet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `insumos_vet` ;

-- -----------------------------------------------------
-- Table `insumos_vet`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`articulos` (
  `id_articulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `fecha_vto` DATE NOT NULL,
  `stock_minimo` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_articulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`sucursales` (
  `id_sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `domicilio` INT NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`id_sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`articulos_x_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`articulos_x_sucursal` (
  `id_articulo` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `sucursal` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_articulo`, `id_estado`, `sucursal`),
  INDEX `id_articulo` (`id_articulo` ASC, `id_estado` ASC, `sucursal` ASC) VISIBLE,
  INDEX `sucursal` (`sucursal` ASC) VISIBLE,
  INDEX `id_estado` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `articulos_x_sucursal_ibfk_1`
    FOREIGN KEY (`sucursal`)
    REFERENCES `insumos_vet`.`sucursales` (`id_sucursal`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `articulos_x_sucursal_ibfk_2`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `insumos_vet`.`articulos` (`id_articulo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `articulos_x_sucursal_ibfk_3`
    FOREIGN KEY (`id_estado`)
    REFERENCES `insumos_vet`.`estados` (`id_estado`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`perfiles` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `perfil` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `perfil` (`perfil` ASC) VISIBLE,
  INDEX `perfil_2` (`perfil` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`perfil`)
    REFERENCES `insumos_vet`.`perfiles` (`id_perfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `dni` INT NOT NULL,
  `usuario` INT NULL DEFAULT NULL,
  `sucursal` INT NOT NULL,
  `mail` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `sucursal` (`sucursal` ASC) VISIBLE,
  CONSTRAINT `empleados_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `insumos_vet`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `empleados_ibfk_2`
    FOREIGN KEY (`sucursal`)
    REFERENCES `insumos_vet`.`sucursales` (`id_sucursal`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`tipos_movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`tipos_movimientos` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_movimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`movimientos` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `id_tipomovimiento` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id_movimiento`),
  INDEX `id_tipomovimiento` (`id_tipomovimiento` ASC, `usuario` ASC) VISIBLE,
  INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `id_movimiento` (`id_movimiento` ASC) VISIBLE,
  CONSTRAINT `movimientos_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `insumos_vet`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `movimientos_ibfk_2`
    FOREIGN KEY (`id_tipomovimiento`)
    REFERENCES `insumos_vet`.`tipos_movimientos` (`id_movimiento`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`movimientos_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`movimientos_detalle` (
  `id_movimiento` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `observacion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_movimiento`, `id_articulo`),
  INDEX `id_movimiento` (`id_movimiento` ASC, `id_articulo` ASC) VISIBLE,
  INDEX `id_articulo` (`id_articulo` ASC) VISIBLE,
  CONSTRAINT `movimientos_detalle_ibfk_1`
    FOREIGN KEY (`id_movimiento`)
    REFERENCES `insumos_vet`.`movimientos` (`id_movimiento`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `movimientos_detalle_ibfk_2`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `insumos_vet`.`articulos` (`id_articulo`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`proveedores` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(30) NOT NULL,
  `mail` VARCHAR(30) NOT NULL,
  `telefono` INT NOT NULL,
  `contacto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`ordenes_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`ordenes_compra` (
  `id_ordencompra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `proveedor` INT NOT NULL,
  `usuario` INT NOT NULL,
  `observaciones` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_ordencompra`),
  INDEX `proveedor` (`proveedor` ASC, `usuario` ASC) VISIBLE,
  INDEX `usuario` (`usuario` ASC) VISIBLE,
  CONSTRAINT `ordenes_compra_ibfk_1`
    FOREIGN KEY (`proveedor`)
    REFERENCES `insumos_vet`.`proveedores` (`id_proveedor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ordenes_compra_ibfk_2`
    FOREIGN KEY (`usuario`)
    REFERENCES `insumos_vet`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`orden_compra_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`orden_compra_detalle` (
  `id_compra` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_compra`, `id_articulo`),
  INDEX `id_compra` (`id_compra` ASC, `id_articulo` ASC) VISIBLE,
  INDEX `id_articulo` (`id_articulo` ASC) VISIBLE,
  CONSTRAINT `orden_compra_detalle_ibfk_1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `insumos_vet`.`ordenes_compra` (`id_ordencompra`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `orden_compra_detalle_ibfk_2`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `insumos_vet`.`articulos` (`id_articulo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`pedidos` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `usuario` (`usuario` ASC) VISIBLE,
  CONSTRAINT `pedidos_ibfk_1`
    FOREIGN KEY (`usuario`)
    REFERENCES `insumos_vet`.`usuarios` (`id_usuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`pedidos_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`pedidos_detalle` (
  `id_pedido` INT NOT NULL,
  `id_articulo` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `observaciones` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_articulo`),
  INDEX `id_pedido` (`id_pedido` ASC, `id_articulo` ASC) VISIBLE,
  INDEX `id_articulo` (`id_articulo` ASC) VISIBLE,
  CONSTRAINT `pedidos_detalle_ibfk_1`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `insumos_vet`.`pedidos` (`id_pedido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `pedidos_detalle_ibfk_2`
    FOREIGN KEY (`id_articulo`)
    REFERENCES `insumos_vet`.`articulos` (`id_articulo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(30) NOT NULL,
  INDEX `id_permiso` (`id_permiso` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `insumos_vet`.`permisos_x_perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insumos_vet`.`permisos_x_perfiles` (
  `id_permiso` INT NOT NULL,
  `id_perfil` INT NOT NULL,
  PRIMARY KEY (`id_permiso`, `id_perfil`),
  INDEX `id_permiso` (`id_permiso` ASC, `id_perfil` ASC) VISIBLE,
  INDEX `id_perfil` (`id_perfil` ASC) VISIBLE,
  CONSTRAINT `permisos_x_perfiles_ibfk_1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `insumos_vet`.`perfiles` (`id_perfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `permisos_x_perfiles_ibfk_2`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `insumos_vet`.`permisos` (`id_permiso`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
